title: Tianci Wang's Homepage
page-top-title: Tianci Wang
top-section-bg-text: Welcome to my personal page
home-subtitle: Tianci Wang&ensp;|&ensp;王天赐
copyright-text: '&copy; Tianci Wang 2025-2025. All Rights Reserved.'
